********************************************************************************
*******************RUN THROUGH CLEANING-NOT ON ITS OWN**************************
********************************************************************************

//Regular vars
label variable hhi_beds "Hospital Market Concentration (Beds)"
label variable hhi_syst_beds "Hospital System Concentration (Beds)"
label variable hhi_dsch "Hospital Market Concentration"
label variable hhi_syst_dsch "Hospital System Concentration"
label variable ins_hhi "Insurer Concentration (Hospital-level)"
label variable ins_st_hhi "Insurer Concentration (State-level)"
label variable log_price "Log of (Procedure Price + 1)"
label variable fp "For-Profit Hospital"
label variable nfp "Not-for-Profit Hospital"
label variable public "Public Hospital"
label variable church "Church Hospital"
label variable hos_ucburden "Uncompensated Care Burden"
label variable price "Procedure Price"
label variable govt "\% Government Payor"
label variable comm "\% Commercial Payors"
label variable cash "\% Self Pay"
label variable price_w "Winsorized Price"
label variable log_price_w "Winsorized Log Price"

//Demeaned vars
label variable hhi_beds_code "Hospital Market Concentration (Beds)"
label variable hhi_syst_beds_code "Hospital System Market Concentration (Beds)"
label variable hhi_dsch_code "Hospital Market Concentration"
label variable hhi_syst_dsch_code "Hospital System Market Concentration"
label variable ins_hhi_code "Insurer Concentration (Hospital-level)"
label variable ins_st_hhi_code "Insurer Concentration (State-level)"
label variable log_price_code "Ln of (Procedure Price+1)"
label variable fp_code "For-Profit Hospital"
label variable public_code "Public Hospital"
label variable church_code "Church Hospital"
label variable hos_ucburden_code "Uncompensated Care Burden"
label variable govt_code "\% Government Payor"
label variable comm_code "\% Commercial Payors"
label variable cash_code "\% Self Pay"

//Interaction Terms
label variable hhi_beds_x_comm "Hospital Market Concentration (Beds)*Commercial Payor"
label variable hhi_syst_beds_x_comm "Hospital System Concentration (Beds)*Commercial Payor"
label variable hhi_dsch_x_comm "Hospital Market Concentration*Commercial Payor"
label variable hhi_syst_dsch_x_comm "Hospital System Concentration*Commercial Payor"
label variable ins_hhi_x_comm "Insurer Concentration (Hospital-level)*Commercial Payor"
label variable ins_st_hhi_x_comm "Insurer Concentration (State-level)*Commercial Payor"
label variable hhi_beds_x_cash "Hospital Market Concentration (Beds)*Cash Price"
label variable hhi_syst_beds_x_cash "Hospital System Concentration (Beds)*Cash Price"
label variable hhi_dsch_x_cash "Hospital Market Concentration*Cash Price"
label variable hhi_syst_dsch_x_cash "Hospital System Concentration*Cash Price"
label variable ins_hhi_x_cash "Insurer Concentration (Hospital-level)*Cash Price"
label variable ins_st_hhi_x_cash "Insurer Concentration (State-level)*Cash Price"
label variable hhi_beds_x_comm_code "Hospital Market Concentration (Beds)*Commercial Payor"
label variable hhi_syst_beds_x_comm_code "Hospital System Market Concentration (Beds)*Commercial Payor"
label variable hhi_dsch_x_comm_code "Hospital Market Concentration*Commercial Payor"
label variable hhi_syst_dsch_x_comm_code "Hospital System Market Concentration*Commercial Payor"
label variable ins_hhi_x_comm_code "Insurer Concentration (Hospital-level)*Commercial Payor"
label variable ins_st_hhi_x_comm_code "Insurer Concentration (State-level)*Commercial Payor"
label variable hhi_beds_x_cash_code "Hospital Market Concentration (Beds)*Cash Price"
label variable hhi_syst_beds_x_cash_code "Hospital System Market Concentration (Beds)*Cash Price"
label variable hhi_dsch_x_cash_code "Hospital Market Concentration*Cash Price"
label variable hhi_syst_dsch_x_cash_code "Hospital System Market Concentration*Cash Price"
label variable ins_hhi_x_cash_code "Insurer Concentration (Hospital-level)*Cash Price"
label variable ins_st_hhi_x_cash_code "Insurer Concentration (State-level)*Cash Price"

//Standardized vars
label variable std_hhi_beds_code "Hospital Market Concentration (Beds)"
label variable std_hhi_syst_beds_code "Hospital System Market Concentration (Beds)"
label variable std_hhi_dsch_code "Hospital Market Concentration"
label variable std_hhi_syst_dsch_code "Hospital System Market Concentration"
label variable std_ins_hhi_code "Insurer Concentration (Hospital-level)"
label variable std_ins_st_hhi_code "Insurer Concentration (State-level)"
label variable std_hhi_beds "Hospital Market Concentration"
label variable std_hhi_syst_beds "Hospital System Concentration"
label variable std_hhi_dsch "Hospital Market Concentration"
label variable std_hhi_syst_dsch "Hospital System Concentration"
label variable std_ins_hhi "Insurer Concentration (Hospital-level)"
label variable std_ins_st_hhi "Insurer Concentration (State-level)"

label variable std_hhi_beds_x_comm "Hospital Market Concentration (Beds)*Commercial Payor"
label variable std_hhi_syst_beds_x_comm "Hospital System Concentration (Beds)*Commercial Payor"
label variable std_hhi_dsch_x_comm "Hospital Market Concentration*Commercial Payor"
label variable std_hhi_syst_dsch_x_comm "Hospital System Concentration*Commercial Payor"
label variable std_ins_hhi_x_comm "Insurer Concentration (Hospital-level)*Commercial Payor"
label variable std_ins_st_hhi_x_comm "Insurer Concentration (State-level)*Commercial Payor"
label variable std_hhi_beds_x_cash "Hospital Market Concentration (Beds)*Cash Price"
label variable std_hhi_syst_beds_x_cash "Hospital System Concentration (Beds)*Cash Price"
label variable std_hhi_dsch_x_cash "Hospital Market Concentration*Cash Price"
label variable std_hhi_syst_dsch_x_cash "Hospital System Concentration*Cash Price"
label variable std_ins_hhi_x_cash "Insurer Concentration (Hospital-level)*Cash Price"
label variable std_ins_st_hhi_x_cash "Insurer Concentration (State-level)*Cash Price"
label variable std_hhi_beds_x_comm_code "Hospital Market Concentration (Beds)*Commercial Payor"
label variable std_hhi_syst_beds_x_comm_code "Hospital System Market Concentration (Beds)*Commercial Payor"
label variable std_hhi_dsch_x_comm_code "Hospital Market Concentration*Commercial Payor"
label variable std_hhi_syst_dsch_x_comm_code "Hospital System Market Concentration*Commercial Payor"
label variable std_ins_hhi_x_comm_code "Insurer Concentration (Hospital-level)*Commercial Payor"
label variable std_ins_st_hhi_x_comm_code "Insurer Concentration (State-level)*Commercial Payor"
label variable std_hhi_beds_x_cash_code "Hospital Market Concentration (Beds)*Cash Price"
label variable std_hhi_syst_beds_x_cash_code "Hospital System Market Concentration (Beds)*Cash Price"
label variable std_hhi_dsch_x_cash_code "Hospital Market Concentration*Cash Price"
label variable std_hhi_syst_dsch_x_cash_code "Hospital System Market Concentration*Cash Price"
label variable std_ins_hhi_x_cash_code "Insurer Concentration (Hospital-level)*Cash Price"
label variable std_ins_st_hhi_x_cash_code "Insurer Concentration (State-level)*Cash Price" 
